services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metubeN
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./Downloads:/downloads
      - ./:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt"}
